/*
-- Query: SELECT * FROM haidao_db.recommend
LIMIT 0, 1000

-- Date: 2014-05-09 20:23
*/
INSERT INTO `recommend` (`id`,`module_id`,`module_desc`,`title`,`content`,`recommend_desc`,`img_url`,`link_url`,`price`,`tel`,`area_id`,`area_name`,`island_id`,`island_name`,`valid`,`big_img_url`,`small_img_url`,`link_obligate`,`price_big`,`price_small`,`create_time`,`create_person`,`upd_time`,`upd_person`,`type_id`,`type_name`,`view_link`,`recommend_index`) VALUES (1,1,'recommond','island_saiban','sai ban','saiban','images/index_side1.jpg','list1.html','20000','1234',1,'saiban',1,'1',1,NULL,NULL,NULL,NULL,NULL,20140507,'test',20140507,'test',1,'1','1',NULL);
INSERT INTO `recommend` (`id`,`module_id`,`module_desc`,`title`,`content`,`recommend_desc`,`img_url`,`link_url`,`price`,`tel`,`area_id`,`area_name`,`island_id`,`island_name`,`valid`,`big_img_url`,`small_img_url`,`link_obligate`,`price_big`,`price_small`,`create_time`,`create_person`,`upd_time`,`upd_person`,`type_id`,`type_name`,`view_link`,`recommend_index`) VALUES (2,1,'recommond','island_saiban','sai ban','saiban','images/index_side2.jpg','list1.html','20000','1234',1,'saiban',1,'1',1,NULL,NULL,NULL,NULL,NULL,20140507,'test',20140507,'test',1,'1','1',NULL);
INSERT INTO `recommend` (`id`,`module_id`,`module_desc`,`title`,`content`,`recommend_desc`,`img_url`,`link_url`,`price`,`tel`,`area_id`,`area_name`,`island_id`,`island_name`,`valid`,`big_img_url`,`small_img_url`,`link_obligate`,`price_big`,`price_small`,`create_time`,`create_person`,`upd_time`,`upd_person`,`type_id`,`type_name`,`view_link`,`recommend_index`) VALUES (3,1,'recommond','island_saiban','sai ban','saiban','images/index_side3.jpg','list1.html','20000','1234',1,'saiban',1,'1',1,NULL,NULL,NULL,NULL,NULL,20140507,'test',20140507,'test',1,'1','1',NULL);
INSERT INTO `recommend` (`id`,`module_id`,`module_desc`,`title`,`content`,`recommend_desc`,`img_url`,`link_url`,`price`,`tel`,`area_id`,`area_name`,`island_id`,`island_name`,`valid`,`big_img_url`,`small_img_url`,`link_obligate`,`price_big`,`price_small`,`create_time`,`create_person`,`upd_time`,`upd_person`,`type_id`,`type_name`,`view_link`,`recommend_index`) VALUES (4,2,'recommond','island_saiban','sai ban','saiban','images/popular/01.png','list1.html','20000','1234',1,'saiban',1,'1',1,'images/popular/01_h.png',NULL,NULL,NULL,NULL,20140507,'test',20140507,'test',1,'1','1',NULL);
INSERT INTO `recommend` (`id`,`module_id`,`module_desc`,`title`,`content`,`recommend_desc`,`img_url`,`link_url`,`price`,`tel`,`area_id`,`area_name`,`island_id`,`island_name`,`valid`,`big_img_url`,`small_img_url`,`link_obligate`,`price_big`,`price_small`,`create_time`,`create_person`,`upd_time`,`upd_person`,`type_id`,`type_name`,`view_link`,`recommend_index`) VALUES (5,2,'recommond','island_saiban','sai ban','saiban','images/popular/02.png','list1.html','20000','1234',1,'saiban',1,'1',1,'images/popular/02_h.png',NULL,NULL,NULL,NULL,20140507,'test',20140507,'test',1,'1','1',NULL);
INSERT INTO `recommend` (`id`,`module_id`,`module_desc`,`title`,`content`,`recommend_desc`,`img_url`,`link_url`,`price`,`tel`,`area_id`,`area_name`,`island_id`,`island_name`,`valid`,`big_img_url`,`small_img_url`,`link_obligate`,`price_big`,`price_small`,`create_time`,`create_person`,`upd_time`,`upd_person`,`type_id`,`type_name`,`view_link`,`recommend_index`) VALUES (6,2,'recommond','island_saiban','sai ban','saiban','images/popular/03.png','list1.html','20000','1234',1,'saiban',1,'1',1,'images/popular/03_h.png',NULL,NULL,NULL,NULL,20140507,'test',20140507,'test',1,'1','1',NULL);
INSERT INTO `recommend` (`id`,`module_id`,`module_desc`,`title`,`content`,`recommend_desc`,`img_url`,`link_url`,`price`,`tel`,`area_id`,`area_name`,`island_id`,`island_name`,`valid`,`big_img_url`,`small_img_url`,`link_obligate`,`price_big`,`price_small`,`create_time`,`create_person`,`upd_time`,`upd_person`,`type_id`,`type_name`,`view_link`,`recommend_index`) VALUES (7,2,'recommond','island_saiban','sai ban','saiban','images/popular/04.png','list1.html','20000','1234',1,'saiban',1,'1',1,'images/popular/04_h.png',NULL,NULL,NULL,NULL,20140507,'test',20140507,'test',1,'1','1',NULL);
INSERT INTO `recommend` (`id`,`module_id`,`module_desc`,`title`,`content`,`recommend_desc`,`img_url`,`link_url`,`price`,`tel`,`area_id`,`area_name`,`island_id`,`island_name`,`valid`,`big_img_url`,`small_img_url`,`link_obligate`,`price_big`,`price_small`,`create_time`,`create_person`,`upd_time`,`upd_person`,`type_id`,`type_name`,`view_link`,`recommend_index`) VALUES (8,2,'recommond','island_saiban','sai ban','saiban','images/popular/05.png','list1.html','20000','1234',1,'saiban',1,'1',1,'images/popular/05_h.png',NULL,NULL,NULL,NULL,20140507,'test',20140507,'test',1,'1','1',NULL);
INSERT INTO `recommend` (`id`,`module_id`,`module_desc`,`title`,`content`,`recommend_desc`,`img_url`,`link_url`,`price`,`tel`,`area_id`,`area_name`,`island_id`,`island_name`,`valid`,`big_img_url`,`small_img_url`,`link_obligate`,`price_big`,`price_small`,`create_time`,`create_person`,`upd_time`,`upd_person`,`type_id`,`type_name`,`view_link`,`recommend_index`) VALUES (9,3,'recommond','马尔代夫婚礼现场1......','sai ban','saiban','images/new.png','list1.html','20000','1234',1,'saiban',1,'1',1,'images/popular/01_h.png',NULL,NULL,NULL,NULL,20140507,'test',20140507,'test',1,'1','1',1);
INSERT INTO `recommend` (`id`,`module_id`,`module_desc`,`title`,`content`,`recommend_desc`,`img_url`,`link_url`,`price`,`tel`,`area_id`,`area_name`,`island_id`,`island_name`,`valid`,`big_img_url`,`small_img_url`,`link_obligate`,`price_big`,`price_small`,`create_time`,`create_person`,`upd_time`,`upd_person`,`type_id`,`type_name`,`view_link`,`recommend_index`) VALUES (10,3,'recommond','马尔代夫婚礼现场2......','sai ban','saiban','images/new.png','list1.html','20000','1234',1,'saiban',1,'1',1,'images/popular/02_h.png',NULL,NULL,NULL,NULL,20140507,'test',20140507,'test',1,'1','1',2);
INSERT INTO `recommend` (`id`,`module_id`,`module_desc`,`title`,`content`,`recommend_desc`,`img_url`,`link_url`,`price`,`tel`,`area_id`,`area_name`,`island_id`,`island_name`,`valid`,`big_img_url`,`small_img_url`,`link_obligate`,`price_big`,`price_small`,`create_time`,`create_person`,`upd_time`,`upd_person`,`type_id`,`type_name`,`view_link`,`recommend_index`) VALUES (11,3,'recommond','马尔代夫婚礼现场3......','sai ban','saiban','','list1.html','20000','1234',1,'saiban',1,'1',1,'images/popular/03_h.png',NULL,NULL,NULL,NULL,20140507,'test',20140507,'test',1,'1','1',3);
INSERT INTO `recommend` (`id`,`module_id`,`module_desc`,`title`,`content`,`recommend_desc`,`img_url`,`link_url`,`price`,`tel`,`area_id`,`area_name`,`island_id`,`island_name`,`valid`,`big_img_url`,`small_img_url`,`link_obligate`,`price_big`,`price_small`,`create_time`,`create_person`,`upd_time`,`upd_person`,`type_id`,`type_name`,`view_link`,`recommend_index`) VALUES (12,3,'recommond','马尔代夫婚礼现场4......','sai ban','saiban','','list1.html','20000','1234',1,'saiban',1,'1',1,'images/popular/04_h.png',NULL,NULL,NULL,NULL,20140507,'test',20140507,'test',1,'1','1',4);
INSERT INTO `recommend` (`id`,`module_id`,`module_desc`,`title`,`content`,`recommend_desc`,`img_url`,`link_url`,`price`,`tel`,`area_id`,`area_name`,`island_id`,`island_name`,`valid`,`big_img_url`,`small_img_url`,`link_obligate`,`price_big`,`price_small`,`create_time`,`create_person`,`upd_time`,`upd_person`,`type_id`,`type_name`,`view_link`,`recommend_index`) VALUES (13,3,'recommond','马尔代夫婚礼现场5......','sai ban','saiban','images/new.png','list1.html','20000','1234',1,'saiban',1,'1',1,'images/popular/05_h.png',NULL,NULL,NULL,NULL,20140507,'test',20140507,'test',1,'1','1',5);
INSERT INTO `recommend` (`id`,`module_id`,`module_desc`,`title`,`content`,`recommend_desc`,`img_url`,`link_url`,`price`,`tel`,`area_id`,`area_name`,`island_id`,`island_name`,`valid`,`big_img_url`,`small_img_url`,`link_obligate`,`price_big`,`price_small`,`create_time`,`create_person`,`upd_time`,`upd_person`,`type_id`,`type_name`,`view_link`,`recommend_index`) VALUES (14,3,'recommond','马尔代夫婚礼现场6......','sai ban','saiban','','list1.html','20000','1234',1,'saiban',1,'1',1,'images/popular/03_h.png',NULL,NULL,NULL,NULL,20140507,'test',20140507,'test',1,'1','1',6);
INSERT INTO `recommend` (`id`,`module_id`,`module_desc`,`title`,`content`,`recommend_desc`,`img_url`,`link_url`,`price`,`tel`,`area_id`,`area_name`,`island_id`,`island_name`,`valid`,`big_img_url`,`small_img_url`,`link_obligate`,`price_big`,`price_small`,`create_time`,`create_person`,`upd_time`,`upd_person`,`type_id`,`type_name`,`view_link`,`recommend_index`) VALUES (15,3,'recommond','马尔代夫婚礼现场7......','sai ban','saiban','','list1.html','20000','1234',1,'saiban',1,'1',1,'images/popular/04_h.png',NULL,NULL,NULL,NULL,20140507,'test',20140507,'test',1,'1','1',7);
INSERT INTO `recommend` (`id`,`module_id`,`module_desc`,`title`,`content`,`recommend_desc`,`img_url`,`link_url`,`price`,`tel`,`area_id`,`area_name`,`island_id`,`island_name`,`valid`,`big_img_url`,`small_img_url`,`link_obligate`,`price_big`,`price_small`,`create_time`,`create_person`,`upd_time`,`upd_person`,`type_id`,`type_name`,`view_link`,`recommend_index`) VALUES (16,3,'recommond','马尔代夫婚礼现场8......','sai ban','saiban','','list1.html','20000','1234',1,'saiban',1,'1',1,'images/popular/04_h.png',NULL,NULL,NULL,NULL,20140507,'test',20140507,'test',1,'1','1',8);
INSERT INTO `recommend` (`id`,`module_id`,`module_desc`,`title`,`content`,`recommend_desc`,`img_url`,`link_url`,`price`,`tel`,`area_id`,`area_name`,`island_id`,`island_name`,`valid`,`big_img_url`,`small_img_url`,`link_obligate`,`price_big`,`price_small`,`create_time`,`create_person`,`upd_time`,`upd_person`,`type_id`,`type_name`,`view_link`,`recommend_index`) VALUES (17,4,'recommond','island_saiban','sai ban','saiban','images/01.jpg','list1.html','20000','1234',1,'saiban',1,'1',1,'images/popular/01_h.png',NULL,NULL,NULL,NULL,20140507,'test',20140507,'test',1,'1','1',NULL);
INSERT INTO `recommend` (`id`,`module_id`,`module_desc`,`title`,`content`,`recommend_desc`,`img_url`,`link_url`,`price`,`tel`,`area_id`,`area_name`,`island_id`,`island_name`,`valid`,`big_img_url`,`small_img_url`,`link_obligate`,`price_big`,`price_small`,`create_time`,`create_person`,`upd_time`,`upd_person`,`type_id`,`type_name`,`view_link`,`recommend_index`) VALUES (18,4,'recommond','island_saiban','sai ban','saiban','images/02.jpg','list1.html','20000','1234',1,'saiban',1,'1',1,'images/popular/02_h.png',NULL,NULL,NULL,NULL,20140507,'test',20140507,'test',1,'1','1',NULL);
INSERT INTO `recommend` (`id`,`module_id`,`module_desc`,`title`,`content`,`recommend_desc`,`img_url`,`link_url`,`price`,`tel`,`area_id`,`area_name`,`island_id`,`island_name`,`valid`,`big_img_url`,`small_img_url`,`link_obligate`,`price_big`,`price_small`,`create_time`,`create_person`,`upd_time`,`upd_person`,`type_id`,`type_name`,`view_link`,`recommend_index`) VALUES (19,4,'recommond','island_saiban','sai ban','saiban','images/01.jpg','list1.html','20000','1234',1,'saiban',1,'1',1,'images/popular/03_h.png',NULL,NULL,NULL,NULL,20140507,'test',20140507,'test',1,'1','1',NULL);
INSERT INTO `recommend` (`id`,`module_id`,`module_desc`,`title`,`content`,`recommend_desc`,`img_url`,`link_url`,`price`,`tel`,`area_id`,`area_name`,`island_id`,`island_name`,`valid`,`big_img_url`,`small_img_url`,`link_obligate`,`price_big`,`price_small`,`create_time`,`create_person`,`upd_time`,`upd_person`,`type_id`,`type_name`,`view_link`,`recommend_index`) VALUES (20,4,'recommond','island_saiban','sai ban','saiban','images/02.jpg','list1.html','20000','1234',1,'saiban',1,'1',1,'images/popular/04_h.png',NULL,NULL,NULL,NULL,20140507,'test',20140507,'test',1,'1','1',NULL);
INSERT INTO `recommend` (`id`,`module_id`,`module_desc`,`title`,`content`,`recommend_desc`,`img_url`,`link_url`,`price`,`tel`,`area_id`,`area_name`,`island_id`,`island_name`,`valid`,`big_img_url`,`small_img_url`,`link_obligate`,`price_big`,`price_small`,`create_time`,`create_person`,`upd_time`,`upd_person`,`type_id`,`type_name`,`view_link`,`recommend_index`) VALUES (21,4,'recommond','island_saiban','sai ban','saiban','images/01.jpg','list1.html','20000','1234',1,'saiban',1,'1',1,'images/popular/05_h.png',NULL,NULL,NULL,NULL,20140507,'test',20140507,'test',1,'1','1',NULL);
INSERT INTO `recommend` (`id`,`module_id`,`module_desc`,`title`,`content`,`recommend_desc`,`img_url`,`link_url`,`price`,`tel`,`area_id`,`area_name`,`island_id`,`island_name`,`valid`,`big_img_url`,`small_img_url`,`link_obligate`,`price_big`,`price_small`,`create_time`,`create_person`,`upd_time`,`upd_person`,`type_id`,`type_name`,`view_link`,`recommend_index`) VALUES (22,4,'recommond','island_saiban','sai ban','saiban','images/02.jpg','list1.html','20000','1234',1,'saiban',1,'1',1,'images/popular/03_h.png',NULL,NULL,NULL,NULL,20140507,'test',20140507,'test',1,'1','1',NULL);
INSERT INTO `recommend` (`id`,`module_id`,`module_desc`,`title`,`content`,`recommend_desc`,`img_url`,`link_url`,`price`,`tel`,`area_id`,`area_name`,`island_id`,`island_name`,`valid`,`big_img_url`,`small_img_url`,`link_obligate`,`price_big`,`price_small`,`create_time`,`create_person`,`upd_time`,`upd_person`,`type_id`,`type_name`,`view_link`,`recommend_index`) VALUES (23,4,'recommond','island_saiban','sai ban','saiban','images/01.jpg','list1.html','20000','1234',1,'saiban',1,'1',1,'images/popular/04_h.png',NULL,NULL,NULL,NULL,20140507,'test',20140507,'test',1,'1','1',NULL);
