--1   首页主推产品
INSERT INTO `haidao_db`.`recommend` ( `module_id`, `module_desc`, `title`, `content`, `DESC`, `img_url`, `link_url`, `price`, `tel`, `area_id`, `area_name`, `island_id`, `island_name`, `index`, `valid`, `create_time`, `create_person`, `upd_time`, `upd_person`, `type_id`, `type_name`, `view_link`) VALUES ( 1, 'recommond', 'island_saiban', 'sai ban', 'saiban', 'images/index_side1.jpg', 'list1.html', '20000', '1234', 1, 'saiban', 1, '1', 1, 1, 20140507, 'test', 20140507, 'test', 1, '1', '1');

INSERT INTO `haidao_db`.`recommend` ( `module_id`, `module_desc`, `title`, `content`, `DESC`, `img_url`, `link_url`, `price`, `tel`, `area_id`, `area_name`, `island_id`, `island_name`, `index`, `valid`, `create_time`, `create_person`, `upd_time`, `upd_person`, `type_id`, `type_name`, `view_link`) VALUES ( 1, 'recommond', 'island_saiban', 'sai ban', 'saiban', 'images/index_side2.jpg', 'list1.html', '20000', '1234', 1, 'saiban', 1, '1', 1, 1, 20140507, 'test', 20140507, 'test', 1, '1', '1');

INSERT INTO `haidao_db`.`recommend` ( `module_id`, `module_desc`, `title`, `content`, `DESC`, `img_url`, `link_url`, `price`, `tel`, `area_id`, `area_name`, `island_id`, `island_name`, `index`, `valid`, `create_time`, `create_person`, `upd_time`, `upd_person`, `type_id`, `type_name`, `view_link`) VALUES ( 1, 'recommond', 'island_saiban', 'sai ban', 'saiban', 'images/index_side3.jpg', 'list1.html', '20000', '1234', 1, 'saiban', 1, '1', 1, 1, 20140507, 'test', 20140507, 'test', 1, '1', '1');
--2 首页最受欢迎岛屿
INSERT INTO `haidao_db`.`recommend` ( `module_id`, `module_desc`, `title`, `content`, `DESC`, `img_url`, `link_url`, `price`, `tel`, `area_id`, `area_name`, `island_id`, `island_name`, `index`, `valid`, `create_time`, `create_person`, `upd_time`, `upd_person`, `type_id`, `type_name`, `view_link`,`big_img_url`) VALUES ( 2, 'recommond', 'island_saiban', 'sai ban', 'saiban', 'images/popular/01.png', 'list1.html', '20000', '1234', 1, 'saiban', 1, '1', 1, 1, 20140507, 'test', 20140507, 'test', 1, '1', '1','images/popular/01_h.png');

INSERT INTO `haidao_db`.`recommend` ( `module_id`, `module_desc`, `title`, `content`, `DESC`, `img_url`, `link_url`, `price`, `tel`, `area_id`, `area_name`, `island_id`, `island_name`, `index`, `valid`, `create_time`, `create_person`, `upd_time`, `upd_person`, `type_id`, `type_name`, `view_link`,`big_img_url`) VALUES ( 2, 'recommond', 'island_saiban', 'sai ban', 'saiban', 'images/popular/02.png', 'list1.html', '20000', '1234', 1, 'saiban', 1, '1', 1, 1, 20140507, 'test', 20140507, 'test', 1, '1', '1','images/popular/02_h.png');

INSERT INTO `haidao_db`.`recommend` ( `module_id`, `module_desc`, `title`, `content`, `DESC`, `img_url`, `link_url`, `price`, `tel`, `area_id`, `area_name`, `island_id`, `island_name`, `index`, `valid`, `create_time`, `create_person`, `upd_time`, `upd_person`, `type_id`, `type_name`, `view_link`,`big_img_url`) VALUES ( 2, 'recommond', 'island_saiban', 'sai ban', 'saiban', 'images/popular/03.png', 'list1.html', '20000', '1234', 1, 'saiban', 1, '1', 1, 1, 20140507, 'test', 20140507, 'test', 1, '1', '1','images/popular/03_h.png');

INSERT INTO `haidao_db`.`recommend` ( `module_id`, `module_desc`, `title`, `content`, `DESC`, `img_url`, `link_url`, `price`, `tel`, `area_id`, `area_name`, `island_id`, `island_name`, `index`, `valid`, `create_time`, `create_person`, `upd_time`, `upd_person`, `type_id`, `type_name`, `view_link`,`big_img_url`) VALUES ( 2, 'recommond', 'island_saiban', 'sai ban', 'saiban', 'images/popular/04.png', 'list1.html', '20000', '1234', 1, 'saiban', 1, '1', 1, 1, 20140507, 'test', 20140507, 'test', 1, '1', '1','images/popular/04_h.png');

INSERT INTO `haidao_db`.`recommend` ( `module_id`, `module_desc`, `title`, `content`, `DESC`, `img_url`, `link_url`, `price`, `tel`, `area_id`, `area_name`, `island_id`, `island_name`, `index`, `valid`, `create_time`, `create_person`, `upd_time`, `upd_person`, `type_id`, `type_name`, `view_link`,`big_img_url`) VALUES ( 2, 'recommond', 'island_saiban', 'sai ban', 'saiban', 'images/popular/05.png', 'list1.html', '20000', '1234', 1, 'saiban', 1, '1', 1, 1, 20140507, 'test', 20140507, 'test', 1, '1', '1','images/popular/05_h.png');

--3    首页咨询内容
INSERT INTO `haidao_db`.`recommend` ( `module_id`, `module_desc`, `title`, `content`, `DESC`, `img_url`, `link_url`, `price`, `tel`, `area_id`, `area_name`, `island_id`, `island_name`, `index`, `valid`, `create_time`, `create_person`, `upd_time`, `upd_person`, `type_id`, `type_name`, `view_link`,`big_img_url`,`recommend_index`) VALUES ( 3, 'recommond', '马尔代夫婚礼现场1......', 'sai ban', 'saiban', 'images/new.png', 'list1.html', '20000', '1234', 1, 'saiban', 1, '1', 1, 1, 20140507, 'test', 20140507, 'test', 1, '1', '1','images/popular/01_h.png',1);

INSERT INTO `haidao_db`.`recommend` ( `module_id`, `module_desc`, `title`, `content`, `DESC`, `img_url`, `link_url`, `price`, `tel`, `area_id`, `area_name`, `island_id`, `island_name`, `index`, `valid`, `create_time`, `create_person`, `upd_time`, `upd_person`, `type_id`, `type_name`, `view_link`,`big_img_url`,`recommend_index`) VALUES ( 3, 'recommond', '马尔代夫婚礼现场2......', 'sai ban', 'saiban', 'images/new.png', 'list1.html', '20000', '1234', 1, 'saiban', 1, '1', 1, 1, 20140507, 'test', 20140507, 'test', 1, '1', '1','images/popular/02_h.png',2);

INSERT INTO `haidao_db`.`recommend` ( `module_id`, `module_desc`, `title`, `content`, `DESC`, `img_url`, `link_url`, `price`, `tel`, `area_id`, `area_name`, `island_id`, `island_name`, `index`, `valid`, `create_time`, `create_person`, `upd_time`, `upd_person`, `type_id`, `type_name`, `view_link`,`big_img_url`,`recommend_index`) VALUES ( 3, 'recommond', '马尔代夫婚礼现场3......', 'sai ban', 'saiban', '', 'list1.html', '20000', '1234', 1, 'saiban', 1, '1', 1, 1, 20140507, 'test', 20140507, 'test', 1, '1', '1','images/popular/03_h.png',3);

INSERT INTO `haidao_db`.`recommend` ( `module_id`, `module_desc`, `title`, `content`, `DESC`, `img_url`, `link_url`, `price`, `tel`, `area_id`, `area_name`, `island_id`, `island_name`, `index`, `valid`, `create_time`, `create_person`, `upd_time`, `upd_person`, `type_id`, `type_name`, `view_link`,`big_img_url`,`recommend_index`) VALUES ( 3, 'recommond', '马尔代夫婚礼现场4......', 'sai ban', 'saiban', '', 'list1.html', '20000', '1234', 1, 'saiban', 1, '1', 1, 1, 20140507, 'test', 20140507, 'test', 1, '1', '1','images/popular/04_h.png',4);

INSERT INTO `haidao_db`.`recommend` ( `module_id`, `module_desc`, `title`, `content`, `DESC`, `img_url`, `link_url`, `price`, `tel`, `area_id`, `area_name`, `island_id`, `island_name`, `index`, `valid`, `create_time`, `create_person`, `upd_time`, `upd_person`, `type_id`, `type_name`, `view_link`,`big_img_url`,`recommend_index`) VALUES ( 3, 'recommond', '马尔代夫婚礼现场5......', 'sai ban', 'saiban', 'images/new.png', 'list1.html', '20000', '1234', 1, 'saiban', 1, '1', 1, 1, 20140507, 'test', 20140507, 'test', 1, '1', '1','images/popular/05_h.png',5);

INSERT INTO `haidao_db`.`recommend` ( `module_id`, `module_desc`, `title`, `content`, `DESC`, `img_url`, `link_url`, `price`, `tel`, `area_id`, `area_name`, `island_id`, `island_name`, `index`, `valid`, `create_time`, `create_person`, `upd_time`, `upd_person`, `type_id`, `type_name`, `view_link`,`big_img_url`,`recommend_index`) VALUES ( 3, 'recommond', '马尔代夫婚礼现场6......', 'sai ban', 'saiban', '', 'list1.html', '20000', '1234', 1, 'saiban', 1, '1', 1, 1, 20140507, 'test', 20140507, 'test', 1, '1', '1','images/popular/03_h.png',6);

INSERT INTO `haidao_db`.`recommend` ( `module_id`, `module_desc`, `title`, `content`, `DESC`, `img_url`, `link_url`, `price`, `tel`, `area_id`, `area_name`, `island_id`, `island_name`, `index`, `valid`, `create_time`, `create_person`, `upd_time`, `upd_person`, `type_id`, `type_name`, `view_link`,`big_img_url`,`recommend_index`) VALUES ( 3, 'recommond', '马尔代夫婚礼现场7......', 'sai ban', 'saiban', '', 'list1.html', '20000', '1234', 1, 'saiban', 1, '1', 1, 1, 20140507, 'test', 20140507, 'test', 1, '1', '1','images/popular/04_h.png',7);

INSERT INTO `haidao_db`.`recommend` ( `module_id`, `module_desc`, `title`, `content`, `DESC`, `img_url`, `link_url`, `price`, `tel`, `area_id`, `area_name`, `island_id`, `island_name`, `index`, `valid`, `create_time`, `create_person`, `upd_time`, `upd_person`, `type_id`, `type_name`, `view_link`,`big_img_url`,`recommend_index`) VALUES ( 3, 'recommond', '马尔代夫婚礼现场8......', 'sai ban', 'saiban', '', 'list1.html', '20000', '1234', 1, 'saiban', 1, '1', 1, 1, 20140507, 'test', 20140507, 'test', 1, '1', '1','images/popular/04_h.png',8);

--4   首页套餐推荐

INSERT INTO `haidao_db`.`recommend` ( `module_id`, `module_desc`, `title`, `content`, `DESC`, `img_url`, `link_url`, `price`, `tel`, `area_id`, `area_name`, `island_id`, `island_name`, `index`, `valid`, `create_time`, `create_person`, `upd_time`, `upd_person`, `type_id`, `type_name`, `view_link`,`big_img_url`) VALUES ( 4, 'recommond', 'island_saiban', 'sai ban', 'saiban', 'images/01.jpg', 'list1.html', '20000', '1234', 1, 'saiban', 1, '1', 1, 1, 20140507, 'test', 20140507, 'test', 1, '1', '1','images/popular/01_h.png');

INSERT INTO `haidao_db`.`recommend` ( `module_id`, `module_desc`, `title`, `content`, `DESC`, `img_url`, `link_url`, `price`, `tel`, `area_id`, `area_name`, `island_id`, `island_name`, `index`, `valid`, `create_time`, `create_person`, `upd_time`, `upd_person`, `type_id`, `type_name`, `view_link`,`big_img_url`) VALUES ( 4, 'recommond', 'island_saiban', 'sai ban', 'saiban', 'images/02.jpg', 'list1.html', '20000', '1234', 1, 'saiban', 1, '1', 1, 1, 20140507, 'test', 20140507, 'test', 1, '1', '1','images/popular/02_h.png');

INSERT INTO `haidao_db`.`recommend` ( `module_id`, `module_desc`, `title`, `content`, `DESC`, `img_url`, `link_url`, `price`, `tel`, `area_id`, `area_name`, `island_id`, `island_name`, `index`, `valid`, `create_time`, `create_person`, `upd_time`, `upd_person`, `type_id`, `type_name`, `view_link`,`big_img_url`) VALUES ( 4, 'recommond', 'island_saiban', 'sai ban', 'saiban', 'images/01.jpg', 'list1.html', '20000', '1234', 1, 'saiban', 1, '1', 1, 1, 20140507, 'test', 20140507, 'test', 1, '1', '1','images/popular/03_h.png');

INSERT INTO `haidao_db`.`recommend` ( `module_id`, `module_desc`, `title`, `content`, `DESC`, `img_url`, `link_url`, `price`, `tel`, `area_id`, `area_name`, `island_id`, `island_name`, `index`, `valid`, `create_time`, `create_person`, `upd_time`, `upd_person`, `type_id`, `type_name`, `view_link`,`big_img_url`) VALUES ( 4, 'recommond', 'island_saiban', 'sai ban', 'saiban', 'images/02.jpg', 'list1.html', '20000', '1234', 1, 'saiban', 1, '1', 1, 1, 20140507, 'test', 20140507, 'test', 1, '1', '1','images/popular/04_h.png');

INSERT INTO `haidao_db`.`recommend` ( `module_id`, `module_desc`, `title`, `content`, `DESC`, `img_url`, `link_url`, `price`, `tel`, `area_id`, `area_name`, `island_id`, `island_name`, `index`, `valid`, `create_time`, `create_person`, `upd_time`, `upd_person`, `type_id`, `type_name`, `view_link`,`big_img_url`) VALUES ( 4, 'recommond', 'island_saiban', 'sai ban', 'saiban', 'images/01.jpg', 'list1.html', '20000', '1234', 1, 'saiban', 1, '1', 1, 1, 20140507, 'test', 20140507, 'test', 1, '1', '1','images/popular/05_h.png');

INSERT INTO `haidao_db`.`recommend` ( `module_id`, `module_desc`, `title`, `content`, `DESC`, `img_url`, `link_url`, `price`, `tel`, `area_id`, `area_name`, `island_id`, `island_name`, `index`, `valid`, `create_time`, `create_person`, `upd_time`, `upd_person`, `type_id`, `type_name`, `view_link`,`big_img_url`) VALUES ( 4, 'recommond', 'island_saiban', 'sai ban', 'saiban', 'images/02.jpg', 'list1.html', '20000', '1234', 1, 'saiban', 1, '1', 1, 1, 20140507, 'test', 20140507, 'test', 1, '1', '1','images/popular/03_h.png');

INSERT INTO `haidao_db`.`recommend` ( `module_id`, `module_desc`, `title`, `content`, `DESC`, `img_url`, `link_url`, `price`, `tel`, `area_id`, `area_name`, `island_id`, `island_name`, `index`, `valid`, `create_time`, `create_person`, `upd_time`, `upd_person`, `type_id`, `type_name`, `view_link`,`big_img_url`) VALUES ( 4, 'recommond', 'island_saiban', 'sai ban', 'saiban', 'images/01.jpg', 'list1.html', '20000', '1234', 1, 'saiban', 1, '1', 1, 1, 20140507, 'test', 20140507, 'test', 1, '1', '1','images/popular/04_h.png');




